### ISSUE TITLE
Map Marker Pointing at Wrong Location

### ISSUE THREAD

**Issue by Shivang-Bhandari** [pythonindia/inpycon2017#100]
The Map Marker included on the website's Home Page is pointing to Rajpath Marg for some reason. Should point to the Venue.

**Comment by realslimshanky** [comment]
The venue has not been confirmed yet. Let's keep this issue open to remind us of this fix to be looked upon when the venue is updated.

**Comment by realslimshanky** [comment]
@Shivang-Bhandari you should close this issue since #107 already takes care of this issue.
Please join the same issue and respective PR if you wish to contribute.

**Comment by Shivang-Bhandari** [comment]
sure
