### ISSUE TITLE
Adding ZeOmega, Adobe and  PSF as Silver Sponsor

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2017#102]
ZeOmega has been confirmed as Silver Sponsor for PyCon India 2017. We need to add the logo of the company on the homepage under 'Sponsor' section.

**Comment by realslimshanky** [comment]
I'm working on this issue and have two layout options to choose from. Please comment your suggestions. cc: @stalwart201 @CuriousLearner @sayanchowdhury 
Option 1 - 
![image](https://user-images.githubusercontent.com/10004530/29870878-34726bfc-8da7-11e7-9158-108bc92d8cbd.png)

Option 2 - 
![image](https://user-images.githubusercontent.com/10004530/29870836-1591023e-8da7-11e7-97c6-239cc4016c4e.png)

**Comment by dotgourav** [comment]
Now that there are more than two sponsors, there isn't much to discuss, isn't it?

**Comment by realslimshanky** [comment]
@Gouravchawla, since we are announcing one sponsor per day, wouldn't it be okay to add one for now?

**Comment by stalwart201** [comment]
Hi Shashank,

I like option second, IMHO we can align the sponsor in center so that when
we add another sponsor next time they will be adjusted accordingly.

Thanks,
Rishabh

**Comment by realslimshanky** [comment]
@stalwart201, okay. that'll do. @Gouravchawla agree?

**Comment by realslimshanky** [comment]
Here's the preview
![image](https://user-images.githubusercontent.com/10004530/29911153-7581da8a-8e4a-11e7-8579-ef0721d496d5.png)

**Comment by dotgourav** [comment]
Well, there is no harm in adding sponsors in one go. We can announce one by one. Are we going to do articles too about each sponsor?

**Comment by realslimshanky** [comment]
@Gouravchawla I don't know about the article.
Here is the final preview.
![image](https://user-images.githubusercontent.com/10004530/29915380-5eeaba58-8e59-11e7-9807-323905269478.png)

**Comment by CuriousLearner** [comment]
Can you try to make the logo blend with the background using opacity?

Also, try to have rounded corner for images if the former does not look good.
