### ISSUE TITLE
Alternate solution is required for Date & Hall/Room tabs on the mobile view

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2017#131]
An alternate solution is required which should take lesser space for both the situations stated below. Please discuss what your solution might be. I suggest a dropdown menu.
On mobile, the Dates in the schedule section looks something like this on the mobile.
![image](https://user-images.githubusercontent.com/10004530/31173234-63558790-a924-11e7-9174-9fac2958e8b1.png)
And the Hall/Room tab looks like.
![image](https://user-images.githubusercontent.com/10004530/31173278-84ec3b60-a924-11e7-91b9-24918b131d55.png)

**Comment by rajataaron** [comment]
ya need to think something alternative
