### ISSUE TITLE
Updating description of talks

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2017#132]
The description of the talks has to be updated on `data/api/tracks.json` which right now only has the title of the talks and events. The description can be picked up from https://in.pycon.org/cfp

**Comment by thisisayush** [comment]
Working on the issue!

**Comment by realslimshanky** [comment]
@thisisayush great. Waiting for your PR.

**Comment by thisisayush** [comment]
Description of talks has been added in #137 
If no changes are to be made, we can close the issue :)

**Comment by realslimshanky** [comment]
@thisisayush true that. Thank you for your contribution :)
