### ISSUE TITLE
Display talk description and speaker info in tentative schedule

### ISSUE THREAD

**Issue by priyankt68** [pythonindia/inpycon2017#136]
Description of selected talks needs to be displayed as mentioned in [CFP page](https://in.pycon.org/cfp/2017/proposals/) along with speaker info.

This could either be :
1. A hyperlink to Junction's page for cfp.
2. An in-place page element - either [bootstrap modal](https://getbootstrap.com/docs/3.3/javascript/#modals) or [bootstrap collapse](https://getbootstrap.com/docs/3.3/javascript/#collapse)

We might need to take care of HTML formatting if pursuing it through in-place page element since speakers tend to use markdown in description of talk proposals.

**Comment by realslimshanky** [comment]
@priyankt68 would you like to work on the issue?

**Comment by priyankt68** [comment]
Sure. I will take up.

I suggest that the easiest to complete this is by hyperlinking to Junction's page for CFP. This way we will have speakers links, talk breakup as well.

So the tracks.json can contain another key with ```link```.
```
"00": {
			"title": "Registration",
			"description": "Register yourselves and get your goodie bag. Have a great day!",
			"type": "default",
                        "link": "http://.....",
			"speaker": {
				"name": "",
				"info": "",
				"photo": "",
                      
			},

		},
```

Suggestions ?

**Comment by realslimshanky** [comment]
@priyankt68 great. Start with a dummy data or maybe data from just one talk while #132 is underway.

**Comment by realslimshanky** [comment]
@priyankt68 thank you for your contribution. I guess this issue is resolved now, closing.
