### ISSUE TITLE
Make sponsor logo center aligned

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2017#149]
Here's the logo of Pipal Academy to shift to center.
![image](https://user-images.githubusercontent.com/10004530/31577216-34fec800-b128-11e7-8603-625fd1f36b61.png)

**Comment by emht** [comment]
I would like to work.

**Comment by realslimshanky** [comment]
@emht great. Waiting for your PR.

**Comment by realslimshanky** [comment]
Since this issue has been fixed in #150 I'm closing it.
