### ISSUE TITLE
in.pycon.org certificate expired 

### ISSUE THREAD

**Issue by abhyudaypratap** [pythonindia/inpycon2017#151]
![image](https://user-images.githubusercontent.com/7920295/31588738-ee7f9c64-b213-11e7-9c80-85fdff3e31b7.png)

**Comment by realslimshanky** [comment]
@abhyudaypratap thank you for raising the issue.
@kracekumar please look into it. :)

**Comment by vipulgupta2048** [comment]
@abhyudaypratap Its fixed. Please check on your end. 
Do close the issue if it does.

**Comment by kracekumar** [comment]
Thank you @realslimshanky and @vipulgupta2048. It's fixed now.
