### ISSUE TITLE
Keynote Speakers redirect to blog posts

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2017#152]
The link on the names of the keynote speakers redirects back to homepage https://in.pycon.org/2017 
As now the blog posts of speakers have been written. The link should redirect there acting as " more information " about that person. That would be more appropriate.  
 

![screenshot_2017-10-16_12-14-17](https://user-images.githubusercontent.com/22801822/31598480-92847788-b26b-11e7-8f95-8889744d24b0.png)

**Comment by realslimshanky** [comment]
@vipulgupta2048 good idea. Would you like to work on this enhancement?

**Comment by vipulgupta2048** [comment]
On it.

**Comment by vipulgupta2048** [comment]
PR #153  Solves this issue. 
Hence closing it.
