### ISSUE TITLE
Unnecessary dots in linking to read full description

### ISSUE THREAD

**Issue by sourabhtk37** [pythonindia/inpycon2017#161]
In the schedule section, the link to read more is prefixed by three dots which look quite bad. The purpose `Read full description` states the obvious. 
![Here's a screenshot for the above](https://user-images.githubusercontent.com/8580742/31840866-d1b3104e-b604-11e7-8175-7644c8671052.png)

The above talk with the dots and below without the talk. Let me know if this seems an unnecessary issue.

**Comment by realslimshanky** [comment]
Look like a good suggestion. Woul you like to submit a PR @sourabhtk37

**Comment by sourabhtk37** [comment]
Well, you already made one. :lollipop:
