### ISSUE TITLE
Blog in a div

### ISSUE THREAD

**Issue by emht** [pythonindia/inpycon2017#181]
All the blog posts are displayed on the homepage which makes it very long to scroll.
The Blog section can be contained within a div with its scroll to make the page look more tidier.

What say, @realslimshanky?

If someone else wants, he can do, else I am doing it.  :)

**Comment by realslimshanky** [comment]
Hi @emht, this issue has already been raised in #163. Please refer that issue and comment there that you're working on it. Thank for picking it up.
