### ISSUE TITLE
Telegram Chat link for voluteers is broken

### ISSUE THREAD

**Issue by emht** [pythonindia/inpycon2017#36]
The llink provided under the Volunteer section to join Telegram group chat seems to be broken and is giving error like

![screenshot_20170714-151515](https://user-images.githubusercontent.com/21521341/28207443-5e184578-68a7-11e7-84a1-6ef4c4690454.png)

**Comment by CuriousLearner** [comment]
Hi @emht, It is working fine for me.  

Can you please try once again?

PS: @realslimshanky Can you check if it works for you?

**Comment by realslimshanky** [comment]
@emht , the telegram group link provided works like perfectly. Try to open [this](https://bit.ly/PyConIndiaVolunteers) link in browser.

**Comment by ashwamegh** [comment]
@realslimshanky @CuriousLearner It is also working fine for me. This issue should be closed for now.

**Comment by CuriousLearner** [comment]
@emht If you face problem, please feel free to reopen this issue

**Comment by emht** [comment]
Well, it seems to work now.  Sorry for wrong intel but I had issues before.
