### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by SpEcHiDe** [pythonindia/inpycon2017#37]
I think the spelling of `sponser` should be `sponsor` instead of `sponser`. 

Reference: https://github.com/pythonindia/inpycon2017/blob/master/index.html#L2477

**Comment by amitsin6h** [comment]
Fixed typo from the index.html @SpEcHiDe . You can close this issue now.

https://github.com/pythonindia/inpycon2017/pull/35/commits/ccdd1b70b7d7e46c9db7b749fdaac4185571b895

**Comment by CuriousLearner** [comment]
@amitsin6h That is not how you mention it in issues. 

You need to first create a PR for us to accept your change. The issue would close automatically when your PR is merged.

**Comment by amitsin6h** [comment]
https://github.com/pythonindia/inpycon2017/pull/44

@SpEcHiDe Now you can merge it. Thanks 👍

**Comment by CuriousLearner** [comment]
PR #57 awaiting changes for this issue.

**Comment by CuriousLearner** [comment]
This is resolved.
