### ISSUE TITLE
Add link for volunteering on the website faq page

### ISSUE THREAD

**Issue by shivakrishna9** [pythonindia/inpycon2017#39]
Link for volunteering registration form is missing in "I want to volunteer ... "
https://pythonindia.github.io/inpycon2017/faqs.html

**Comment by krishamehta** [comment]
Form link added

**Comment by shivakrishna9** [comment]
Thanks @krishamehta . please submit a pull request.

**Comment by krishamehta** [comment]
@shivakrishna9  Done.

**Comment by realslimshanky** [comment]
@krishamehta you can also link the issue with your PR by simply adding the issue no with #.
This makes it easier to track.

**Comment by realslimshanky** [comment]
@CuriousLearner we can close this issue. It's been fixed in #74
