### ISSUE TITLE
Add CNAME to permanently redirect to custom domain

### ISSUE THREAD

**Issue by sourabhtk37** [pythonindia/inpycon2017#43]
Current gh-page is not resolving to `https://in.pycon.org/2017/` which needs to be the case.

**Comment by CuriousLearner** [comment]
@sourabhtk37 is not hosted on Github. So, this doesn't make sense.

**Comment by sourabhtk37** [comment]
https://pythonindia.github.io/inpycon2017/
I thought so too since there was no `gh-page` branch.

**Comment by CuriousLearner** [comment]
@sourabhtk37 We will wait for this issue to be cleared with the deployment team.

**Comment by rajataaron** [comment]
@sourabhtk37 that link is for the stagging website check.

**Comment by sourabhtk37** [comment]
Alright. Closing this.
