### ISSUE TITLE
Is this image supposed to look like this?

### ISSUE THREAD

**Issue by geekodour** [pythonindia/inpycon2017#47]
![image](https://i.imgur.com/M1vmLLM.png)

**Comment by geekodour** [comment]
I didn't check it on phone, if it shows up like this on phone it will look a bit weird I think.

**Comment by geekodour** [comment]
let me know, if I should send a PR for this, for smaller devices.

**Comment by CuriousLearner** [comment]
@rajataaron Can you please reply here?

**Comment by rajataaron** [comment]
the image is like this only on both desktop and mobile if it looks weird then let me see what i can do

**Comment by realslimshanky** [comment]
@geekodour It's design! ;)

**Comment by rajataaron** [comment]
@geekodour if it's look odd then do provide the better solution if we find your solution is appropriate then we will use that.

**Comment by CuriousLearner** [comment]
This is intended. Closing it for now.
