### ISSUE TITLE
Contributor Request

### ISSUE THREAD

**Issue by s1db** [pythonindia/inpycon2017#5]
Hello! I want to help out in making the site. If possible could you assign me a task?

**Comment by shagunsodhani** [comment]
Hey @cosmicAsymmetry I do not see any open issues for now but I am sure the organising team has plenty of website-related things to take care of.  You may fill the [volunteer form](http://bit.ly/inpycon2017) and select `Website Development` as your domain. Alternatively, feel free to report and fix things that you feel needs to be improved. It could be as simple as some missing information which you feel is relevant.

**Comment by CuriousLearner** [comment]
I think @shagunsodhani has provided the details :)

Closing this for now!
