### ISSUE TITLE
Is the logo too small

### ISSUE THREAD

**Issue by vkmrishad** [pythonindia/inpycon2017#53]
Did anyone think the logo is small.
![screen shot 2017-07-15 at 7 07 17 pm](https://user-images.githubusercontent.com/18536460/28239764-d85b7ea6-6990-11e7-9cd6-d806537726ca.png)

**Comment by mish24** [comment]
It actually is. The PyCon one on top right? @CuriousLearner Whar do you think?

**Comment by CuriousLearner** [comment]
@vkmrishad @mish24 Why do you think the logo is small?

Can you paste a screenshot here of how much big you think the logo should be?

**Comment by vkmrishad** [comment]
Its just my opinion. 
250x56

![screen shot 2017-07-16 at 9 11 27 pm](https://user-images.githubusercontent.com/18536460/28249006-bafce756-6a6b-11e7-8425-04fa86f01e80.png)

**Comment by CuriousLearner** [comment]
Seems okay to me. @rajataaron  What do you think?

**Comment by rajataaron** [comment]
the logo is at its maximum size. there is a reason that we can not increase its size

**Comment by realslimshanky** [comment]
@vkmrishad  Logo looks good at this size. If you compare it with the other elements of the navbar you'll start to embrace it.

**Comment by CuriousLearner** [comment]
@rajataaron Should we close this issue then?

**Comment by rajataaron** [comment]
@CuriousLearner yes close this issue logo is of fit size there is no problem with it. I have tested it on all devices after this issue.
