### ISSUE TITLE
Add keynote speakers

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2017#54]
Since Noufal Ibrahim and Peter Wang are confirmed as keynote we should add their details on the homepage.

**Comment by ashwamegh** [comment]
Should I add it.. @realslimshanky  ?

**Comment by realslimshanky** [comment]
@shashank7200 sure, since you already have a PR in line waiting for the review make sure you start clean for this issue. There has been situations of mix-up.

**Comment by ashwamegh** [comment]
@realslimshanky From where should I get the images and links of speakers, Or simply get it from Internet ?

**Comment by realslimshanky** [comment]
Ask from the design team off the mailing list and also try to get one yourself if in better quality.

**Comment by CuriousLearner** [comment]
@rajataaron Please do the needful.

**Comment by rajataaron** [comment]
As of right now we are asking from both the keynotes for their pictures till then this thing is on halt.

**Comment by CuriousLearner** [comment]
PR merged #87
