### ISSUE TITLE
The arrow must point down.

### ISSUE THREAD

**Issue by Xizt** [pythonindia/inpycon2017#55]
I feel the arrow must point down when more is yet to be clicked and on clicking , upwards.
![imageedit_2_8760434586](https://user-images.githubusercontent.com/19890659/28242627-469df26c-69ce-11e7-9c7a-8d5f00b24ee2.jpg)

**Comment by Xizt** [comment]
Created a pull request for the same

**Comment by CuriousLearner** [comment]
This seems good, I will review the request today. Thanks for your contribution.
