### ISSUE TITLE
Speakers, 4 days event section gets left aligned at certain resolutions

### ISSUE THREAD

**Issue by Xizt** [pythonindia/inpycon2017#56]
![issue](https://user-images.githubusercontent.com/19890659/28242676-ac83b480-69cf-11e7-9da1-32466d98978d.png)

**Comment by mish24** [comment]
Yes.
![screenshot from 2017-07-16 12-45-19](https://user-images.githubusercontent.com/24610197/28245457-b1625966-6a24-11e7-8402-9b52b4e15b0c.png)

Is this size too big for the speakers?

**Comment by Xizt** [comment]
Yep, at this certain resolution the images stay bigger, the above section gets left aligned.

**Comment by CuriousLearner** [comment]
We shall look into this once the speakers' section is updated.

The left aligned 4 days event section should be centered. While working on the PR please ensure to have a minimal number of break points.

**Comment by pradeepgangwar** [comment]
I am working on this issue as I was the one who previously amended the statistics section mobile view.
As said by @CuriousLearner speakers' section will be updated once list is updated. So for now i am working on statistics section.

**Comment by pradeepgangwar** [comment]
#61 merged. Can be closed now .

**Comment by CuriousLearner** [comment]
Speaker section can be worked upon now, if the issue persists for it.

**Comment by realslimshanky** [comment]
@CuriousLearner this issue can be closed now since it's been fixed in #61

**Comment by CuriousLearner** [comment]
Does speaker section work on small screens?

**Comment by realslimshanky** [comment]
Speaker section is meant to scale on the mobile view accordingly. If someone comes us with a better UI for  the speaker section then we can open this issue again or create another one.
