### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by vkmrishad** [pythonindia/inpycon2017#59]
Please add a favicon :)

**Comment by CuriousLearner** [comment]
@rajataaron Can you please update a favicon for the site from Design team so that this can be resolved in a PR?

**Comment by rajataaron** [comment]
ya sure i will fix this tonight...

**Comment by CuriousLearner** [comment]
@rajataaron Can you please provide a link to favicon here so one of the contributors can pick up the task and make a PR corresponding to this issue?

**Comment by rajataaron** [comment]
@vkmrishad @CuriousLearner here is the link to favicon feel free to use this and do PR  https://goo.gl/RzUpNp

**Comment by ramakanthd92** [comment]
Hi, I am working on adding the favicon to the website

**Comment by ramakanthd92** [comment]
Submitted a pull request https://github.com/pythonindia/inpycon2017/pull/63
