### ISSUE TITLE
Make gallery live again!

### ISSUE THREAD

**Issue by CuriousLearner** [pythonindia/inpycon2017#62]
Since we are awaiting review from people to use their photographs on the website, gallery was hidden in my commit 89066fe7fed5e8f58e51161d65727057827bbe57

We need to make gallery live again so that other gallery related issues could be taken care of.

**Comment by Xizt** [comment]
I'll do it

**Comment by CuriousLearner** [comment]
@Xizt This is still waiting for the consent and updates. Not doable at the moment.

**Comment by Xizt** [comment]
Ok. Considering the atomic PR I thought this issue is to just add the gallery list items to the pages
