### ISSUE TITLE
Speakers Link in Menu points to Root 

### ISSUE THREAD

**Issue by thisisayush** [pythonindia/inpycon2017#64]
Link to Speakers section points to /#speakers instead of #speakers which is causing the issues when working in subdirectory root (e.g. localhost/git/inpycon2017/).

**Comment by sagarchoudhary96** [comment]
Hey , I have fixed this one , can i send the PR?

**Comment by amitsin6h** [comment]
but this works well in localhost @thisisayush

**Comment by rajataaron** [comment]
Ya so, I have already fixed that so I am closing this issue
