### ISSUE TITLE
animate.css is Included but not used

### ISSUE THREAD

**Issue by Xizt** [pythonindia/inpycon2017#67]

**Comment by Xizt** [comment]
created a PR for the same.

**Comment by rajataaron** [comment]
We are collecting the merged files and deploy them by tonight after that it will reflect on URL.

**Comment by Xizt** [comment]
@rajataaron please look at PR #68 . It makes use of the above library.

**Comment by realslimshanky** [comment]
@CuriousLearner this can be closed since the animations added on #68 make use of animate.css.
