### ISSUE TITLE
Hero Screen is much larger than the browser height

### ISSUE THREAD

**Issue by Shivang-Bhandari** [pythonindia/inpycon2017#72]
I think the Hero section should have a maximum height of 100vh whereas it is exceeding it.

**Comment by rajataaron** [comment]
@Shivang-Bhandari I got your problem, even you can fix that and create a issue.

**Comment by Shivang-Bhandari** [comment]
@rajataaron I'll be more than happy to contribute. Will fix and put up a PR

**Comment by realslimshanky** [comment]
@Shivang-Bhandari you need to make a PR from your repo to master of inpycon2017 repo in order to fix the issue.

**Comment by rajataaron** [comment]
issue resolved i am closing this issue

**Comment by rajataaron** [comment]
issue resolved i am closing this issue
