### ISSUE TITLE
[URGENT] Update ticket FAQ

### ISSUE THREAD

**Issue by CuriousLearner** [pythonindia/inpycon2017#84]
Update ticket FAQ from this information:

Policy for ticket transfer & cancellation:

- All tickets are transferable.

- Early bird tickets cannot be canceled. They can only be transferred.

- All other tickets can be canceled till 10th Oct 2017.

- Tickets can be transferred till 10th Oct 2017 using the ticket transfer link .

**Comment by stalwart201** [comment]
@realslimshanky  Working on it.

**Comment by realslimshanky** [comment]
Yeah. I am working to resolve this issue. Sending a PR soon.

**Comment by CuriousLearner** [comment]
May be you can break it up in different FAQs
