### ISSUE TITLE
Fixing typos on faqs.html

### ISSUE THREAD

**Issue by abhiramr** [pythonindia/inpycon2017#88]
- Fixing "  - PyCon India T-shirt which will be distributed on Sep 25." to reflect the second day of the conference in 2017 i.e Nov 3rd
- Minor typos fixed

**Comment by realslimshanky** [comment]
This issue is duplicate of #84

**Comment by abhiramr** [comment]
I'd looked into the commits for #84 and they seemed to have missed these bits out though. Am I mistaken?

**Comment by realslimshanky** [comment]
Since that issue is solving the similar bug if you have any additional query you can comment there also. I've fixed the typo on that issue.

**Comment by abhiramr** [comment]
Alright, just saw the comment on the PR. No worries then.
