### ISSUE TITLE
[UX/UI] Icon overlaps "Buy Tickets" button on mobile view

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2017#90]
Below is the screenshot of the issue. This can be fixed my making the button size smaller for mobile view.
![image](http://i.imgur.com/qOHxlS8.png)

**Comment by withshubh** [comment]
Fixed!

**Comment by realslimshanky** [comment]
@withshubh, here are few things I reviewed.
1) You have created two separate branches with same fix on both of them. Only one is enough.
2) You'll have send PR (Pull Request) from either of the branches of your [forked repository](https://github.com/withshubh/inpycon2017) to the master branch of original repository.
3) Your fix has made the icon look smaller on the desktop version of website as well. The bug is only on the mobile view. You'll have to use media queries in your css to target only the mobile view.
Feel free to question in case of any confusion.

**Comment by realslimshanky** [comment]
@CuriousLearner this can be closed and the issue is resolved and merged in #95
