### ISSUE TITLE
Blog feed alogside/after twitter feed

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2017#99]
Just like the twitter feed, a blog feed would be helpful to get the latest blogs form 2017 from in.pycon.org/blog

**Comment by Ayukha** [comment]
I would like to contribute on this issue.

**Comment by realslimshanky** [comment]
Sure @Ayukha go ahead, clone the repository and fork your clone to local machine. Follow guidelines given in README.md

**Comment by realslimshanky** [comment]
@Ayukha are you working on the issue?
